# ----------------------- #
#      Main Config        #
# ----------------------- #

url: "https://meefik.github.io"
title: "Meefik's Blog"
subtitle: "Freedom and Open Source"
description: "Thoughts, tutorials and ideas about programming, technology and open source."
author: "Anton Skshidlevsky"
author_url: "/about"
email: "meefik [at] gmail.com"
locale: "en_US"
simple_search: "https://www.google.com/search"
permalink: "/:year/:month/:day/:title/"
markdown: "kramdown"
highlighter: "rouge"
paginate: 10
paginate_path: "posts/:num"
excerpt_link: "Read on &rarr;"
excerpt_separator: "<!--more-->"
edit: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github
github_user: meefik
github_repo: meefik.github.io

# Youtube
youtube_user: meefik

# LinkedIn
linkedin_user: meefik

# Disqus Comments
disqus_short_name: meefik

webmaster_verifications:
  google: dGJ6VfcCIScnbBvYNzNsa7jnV5AoX60mv6eoQIEIYk0
